title: Francesco's website
description: > # this means to ignore newlines until "baseurl:"
  Personal website of Francesco Seccamonte, PhD student at UCSB.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://francescoseccamonte.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Francesco Seccamonte # add your name
author-img: francesco-seccamonte.png # add your photo
about-author: PhD student in Mechanical Engineering at UC Santa Barbara. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: francescoseccamonte # add your Github handle
social-linkedin: francescoseccamonte # add your Linkedin handle
social-scholar: 7ZXfuAMAAAAJ # add your Google scholar user
social-email: fseccamonte # add your Email
social-email-domain: ucsb.edu # add your Email domain

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
